### ISSUE TITLE
Net::IMAP::BadResponseError: User is authenticated but not connected

### ISSUE THREAD

**Issue by melish** [beam/redmine-email-oauth#8]
I was able to generate the account token using redmine:email:o365_oauth2_init, but when running receive_imap_oauth2 I get this error, after imap.authenticate
```
# p imap.authenticate(auth_type, imap_options[:username], password)
#<struct Net::IMAP::TaggedResponse tag="RUBY0002", name="OK", data=#<struct Net::IMAP::ResponseText code=nil, text="AUTHENTICATE completed.">, raw_data="RUBY0002 OK AUTHENTICATE completed.\r\n">

rake aborted!
Net::IMAP::BadResponseError: User is authenticated but not connected. (Net::IMAP::BadResponseError)

/usr/local/bundle/gems/net-imap-0.3.7/lib/net/imap.rb:2172:in `get_tagged_response'
/usr/local/bundle/gems/net-imap-0.3.7/lib/net/imap.rb:2224:in `block in send_command'
/usr/local/bundle/gems/net-imap-0.3.7/lib/net/imap.rb:2206:in `send_command'
/usr/local/bundle/gems/net-imap-0.3.7/lib/net/imap.rb:1215:in `block in list'
/usr/local/bundle/gems/net-imap-0.3.7/lib/net/imap.rb:1214:in `list'
/usr/src/redmine/lib/redmine/imap.rb:65:in `check'
```

in my case `imap.rb:65` uses the `imap.list("", "*")` method, but the same errors happens for `imap.select(folder)` or any other imap methods.

Any idea why this would happen?

**Comment by melish** [comment]
I figured it out eventually. The problem was that when initializing the oauth token, I was logged in O365 with a different account (domain admin) instead of the actual exchange user used by redmine to fetch emails.
